### ISSUE TITLE
Strange behaviour with partial fail

### ISSUE THREAD

**Issue by nyaapa** [allure-framework/allure-scalatest#10]
I have [added](https://github.com/nyaapa/allure-scalatest-example/commit/c6e88839f388b65cc4af2573545575018c55c9a9) simple test that always fails

As a result i got

```
  [info] Run completed in 344 milliseconds.
  [info] Total number of tests run: 3
  [info] Suites: completed 2, aborted 0
  [info] Tests: succeeded 2, failed 1, canceled 0, ignored 0, pending 0
  [info] *** 1 TEST FAILED ***
```

and

``` xml
  ...
  </test-case>
  <test-case start="1424395967702" stop="1424395967702" status="passed">
  <name>A Stack should throw NoSuchElementException if an empty stack is popped</name>
  <failure>
  <message>TestFailedException: 42</message>
  <stack-trace>org.scalatest.exceptions.TestFailedException: 42
  ...
```

in target/allure-report/*.xml

*_Everything is ok when everything fails_

**Comment by vania-pooh** [comment]
What I can see from the XML results is that for some reason test case from one spec gets written to the XML corresponding to the second spec. This can relate to https://github.com/scalatest/scalatest/issues/432

**Comment by vania-pooh** [comment]
Got it. This an issue in allure-scalatest related to the fact that Scalatest runs tests in parallel and events are thrown from multiple threads. As a temporary solution you can insert the following line to build.sbt:
```scala
parallelExecution in ThisBuild := false
```
This will however turn off parallel tests execution (http://stackoverflow.com/questions/11899723/how-to-turn-off-parallel-execution-of-tests-for-multi-project-builds). Will fix this when I have some more free time.

**Comment by vania-pooh** [comment]
@baev any idea how to handle the following sequence of events:
```
TestSuiteStarted 1
TestSuiteStarted 2
TestCaseStarted A
TestCaseStarted B
TestCaseStarted C
TestCaseFailed B
TestCaseFinished A
...
```

**Comment by nyaapa** [comment]
no news yet?

**Comment by vania-pooh** [comment]
@nyaapa unfortunately not yet.

**Comment by pmryhlotskyi** [comment]
I've fixed trhis bug changing the code as below:
`private def testCaseFailed(throwable: Throwable) {
    println(s"Test failed with exception ${throwable.getClass.getCanonicalName}")
    lifecycle.fire(new TestCaseFailureEvent().withThrowable(throwable))
    testCaseFinished
  }`

**Comment by vania-pooh** [comment]
Feel free to send a PR then.
