### ISSUE TITLE
SBT hangs at the enf of test with no report generation

### ISSUE THREAD

**Issue by ShettyA** [allure-framework/allure-scalatest#12]
I am running into this issue where at the end of test execution, sbt just hangs with no reports generated. Anyone else running into this or any pointers to help resolve this?

Some details from my build.sbt for reference.
`scalaVersion := "2.10.4"
libraryDependencies ++= Seq(
  "com.github.scopt" %% "scopt" % "3.3.0" excludeAll (
    ExclusionRule(organization = "asm")
  ),
  "org.json4s" %% "json4s-jackson" % "3.2.7" excludeAll (
    ExclusionRule(organization = "asm")
  ),
   "org.apache.hadoop" % "hadoop-core" % "1.2.1" excludeAll (
    ExclusionRule(organization = "asm")
  ),
  "org.apache.hive"   % "hive-jdbc"     % "0.12.0-cdh5.0.0" excludeAll(
    ExclusionRule(organization = "asm")
  ),
  "org.scalatest" %% "scalatest" % "2.2.5" % "test->*" excludeAll (
    ExclusionRule(organization="org.junit", name="junit"),
    ExclusionRule(organization = "asm")
  ),
  "org.slf4j" % "slf4j-log4j12" % "1.6.2" excludeAll (
    ExclusionRule(organization = "asm")
  ),
  "ru.yandex.qatools.allure" % "allure-scalatest_2.10" % "1.4.0-SNAPSHOT" % "test",
   "asm" % "asm-all" % "3.1" force()
)
fork in Test := false
parallelExecution in ThisBuild := false
resolvers ++= Seq(
  "Ooyala Nexus Releases" at "http://nexus.ooyala.com/nexus/content/repositories/releases/",
  "Ooyala Nexus Snapshots" at "http://nexus.ooyala.com/nexus/content/repositories/snapshots/",
  "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
  "Ooyala Nexus Public" at "http://nexus.ooyala.com/nexus/content/groups/public/"
)
testOptions in Test ++= Seq(
  Tests.Argument(TestFrameworks.ScalaTest, "-oD"),
  Tests.Argument(TestFrameworks.ScalaTest, "-C", "ru.yandex.qatools.allure.scalatest.AllureReporter")
)
`

**Comment by vania-pooh** [comment]
@ShettyA we don't actively develop this stuff. So no ideas. Sorry.

**Comment by ivanpeng** [comment]
This might be really delayed, but I ran into this issue as well, and this was the stack trace: 

    [ERROR] java.lang.NoSuchMethodError: org.apache.commons.beanutils.ConvertUtilsBean.register(ZZI)V
    [ERROR] at ru.yandex.qatools.properties.decorators.DefaultFieldDecorator.<init>(DefaultFieldDecorator.java:24)


Turns out I was missing that dependency. Add this to your build.sbt:

`libraryDependencies += "commons-beanutils" % "commons-beanutils" % "1.9.3"`

And you should be okay.
