### ISSUE TITLE
How to use @Step annotation together with allure-scalatest in multi libraries project

### ISSUE THREAD

**Issue by azakordonets** [allure-framework/allure-scalatest#19]
Hi. We have a number of projects with different API tests. This tests can re-use some common API clients for their purposes. We managed to add allure tests for this projects, however we would like to log and include http calls/responces into the report. I tried to do next : 
```scala
trait AllureLogger extends LazyLogging {

  @Step("{0}")
  def debugLog(stepDescription: String, attachmentText: String = null): Unit = {
    logger.debug(s"$stepDescription $attachmentText")
    if (attachmentText != null) attachMessage(attachmentText)
  }

  @Attachment
  def attachMessage(message: String): String = {
    message
  }
}
```

I use `debugLog` in our tests, but when i try to generate report, i only see errors and not logged information inside the reported test. 

Any tips on how to achieve this ?

**Comment by alexandr85** [comment]
Hello @azakordonets What about `Step` annotation in simple project? Do you see steps in report?

**Comment by azakordonets** [comment]
Hey, sorry but i got away from Scala tests, so can't check it anymore.
