### ISSUE TITLE
scalatest 2.11 support

### ISSUE THREAD

**Issue by Elufimov** [allure-framework/allure-scalatest#9]
Any plans for add compatibility with scalatest 2.11?

**Comment by vania-pooh** [comment]
@Elufimov so far as there is no real demand for this stuff we don't develop it. I could just update dependency version if you wish. :)

**Comment by Elufimov** [comment]
@vania-pooh Yes, it will be great. Right now i have 
```
[error] Modules were resolved with conflicting cross-version suffixes in {file:/Users/elufimov/Documents/Projects/Scala/WebUITests/}webuitests:
[error]    org.scalatest:scalatest _2.11, _2.10
```

**Comment by vania-pooh** [comment]
@Elufimov it would be great if you send me a PR for Scalatest which seems to work for you. I don't have deep SBT knowledge, so if there's some elegant way to support both 2.10 and 2.11 then I would just merge your fix.

**Comment by vanclist** [comment]
Still no plans to move to Scala 2.11?

**Comment by vania-pooh** [comment]
Still waiting for hero that will provide a PR...

**Comment by azakordonets** [comment]
Any idea on when you guys gonna publish it? I see that PR was merged already

**Comment by vania-pooh** [comment]
Summon @baev.

**Comment by azakordonets** [comment]
@baev @vania-pooh any chance you guys will publish it in the nearest future? :)

**Comment by akaAXeL** [comment]
UP

**Comment by eroshenkoam** [comment]
I will do it tomorow)

**Comment by azakordonets** [comment]
@eroshenkoam So, how did it go? :) I don't see updates in README file and cannot find new artifact on maven central repository :)

**Comment by eroshenkoam** [comment]
@azakordonets I need help with building project. 
https://ci.qameta.io/job/allure-scalatest/job/pipeline/5/console

Can you help me?

**Comment by eroshenkoam** [comment]
@azakordonets i fix it when update version of missing plugin to 2.7.4
https://ci.qameta.io/job/allure-scalatest/job/pipeline/9/console

**Comment by eroshenkoam** [comment]
@azakordonets I made the release, but sonatype wasn't accept this because missing javadoc. So I will make release if you help me generate javadoc.jar

**Comment by eroshenkoam** [comment]
@azakordonets the simplest way is create `-javadoc.jar` with README.md content only. Can you make pr with such task for me?

**Comment by azakordonets** [comment]
Yeah, i'm on it

**Comment by azakordonets** [comment]
@eroshenkoam check it out - https://github.com/allure-framework/allure-scalatest/pull/15

**Comment by eroshenkoam** [comment]
@azakordonets https://oss.sonatype.org/#nexus-search;quick~allure-scalatest

**Comment by eroshenkoam** [comment]
Now we cant release scalatest just in few minutes :)

**Comment by azakordonets** [comment]
@eroshenkoam please tell me that you mistyped and you meant `cant release` :)

**Comment by eroshenkoam** [comment]
@azakordonets sure :)
